/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSlider>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QLabel *lbOriginalImageDisplay;
    QLabel *lbOriginalImageDisplay_cORr;
    QLabel *lbOriginalImageDisplay_mORg;
    QLabel *lbOriginalImageDisplay_yORb;
    QLabel *lbOriginalImageDisplay_k;
    QLabel *lbColor1;
    QLabel *lbColor2;
    QLabel *lbColor3;
    QLabel *lbColor4;
    QPushButton *pBstartLayering;
    QPushButton *pBloadImage;
    QDoubleSpinBox *dSBcAdjustmentCoefficient;
    QDoubleSpinBox *dSBmAdjustmentCoefficient;
    QDoubleSpinBox *dSByAdjustmentCoefficient;
    QDoubleSpinBox *dSBkAdjustmentCoefficient;
    QPushButton *pBsaveScheme;
    QLabel *label_23;
    QPushButton *pbNewScheme;
    QCheckBox *cbStartInScheme;
    QPushButton *pbOpenScheme;
    QPushButton *pBsaveSchemeAs;
    QLineEdit *leSchemeDameDisplay;
    QSlider *hSColorSaturation;
    QLabel *label_5;
    QLabel *lbColorSaturationDisplay;
    QLabel *label_13;
    QLabel *lbImageName;
    QSpinBox *sBccOriginal;
    QSpinBox *sBcmOriginal;
    QSpinBox *sBcyOriginal;
    QSpinBox *sBmmOriginal;
    QSpinBox *sBmyOriginal;
    QSpinBox *sBmcOriginal;
    QSpinBox *sBymOriginal;
    QSpinBox *sByyOriginal;
    QSpinBox *sBycOriginal;
    QDoubleSpinBox *dsbLineDistanceC;
    QLabel *label_7;
    QDoubleSpinBox *dsbLineDistanceM;
    QLabel *label_12;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QDoubleSpinBox *dsbLineDistanceY;
    QLabel *label_15;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_16;
    QDoubleSpinBox *dsbLineDistanceK;
    QComboBox *cmbDrawLnType;
    QLabel *label;
    QSpinBox *sbGrayLevel;
    QLabel *label_8;
    QLabel *label_11;
    QSpinBox *sBimageHeight;
    QCheckBox *cBblackLayering;
    QLabel *label_14;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QGroupBox *groupBox;
    QComboBox *cmBpenNumC;
    QComboBox *cmBpenNumM;
    QComboBox *cmBpenNumY;
    QComboBox *cmBpenNumK;
    QCheckBox *cBSelectMorG;
    QCheckBox *cBSelectCorR;
    QCheckBox *cBSelectYorB;
    QCheckBox *cBSelectK;
    QMenuBar *menuBar;
    QMenu *menu;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1000, 736);
        MainWindow->setStyleSheet(QString::fromUtf8("border-color: transparent;\n"
""));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        lbOriginalImageDisplay = new QLabel(centralWidget);
        lbOriginalImageDisplay->setObjectName(QString::fromUtf8("lbOriginalImageDisplay"));
        lbOriginalImageDisplay->setGeometry(QRect(24, 132, 324, 324));
        lbOriginalImageDisplay->setStyleSheet(QString::fromUtf8("background-color:rgb(200, 200, 200)"));
        lbOriginalImageDisplay_cORr = new QLabel(centralWidget);
        lbOriginalImageDisplay_cORr->setObjectName(QString::fromUtf8("lbOriginalImageDisplay_cORr"));
        lbOriginalImageDisplay_cORr->setGeometry(QRect(445, 132, 138, 138));
        lbOriginalImageDisplay_cORr->setStyleSheet(QString::fromUtf8("background-color:rgb(200, 200, 200)"));
        lbOriginalImageDisplay_cORr->setMargin(0);
        lbOriginalImageDisplay_mORg = new QLabel(centralWidget);
        lbOriginalImageDisplay_mORg->setObjectName(QString::fromUtf8("lbOriginalImageDisplay_mORg"));
        lbOriginalImageDisplay_mORg->setGeometry(QRect(700, 132, 141, 141));
        lbOriginalImageDisplay_mORg->setStyleSheet(QString::fromUtf8("background-color:rgb(200, 200, 200)"));
        lbOriginalImageDisplay_yORb = new QLabel(centralWidget);
        lbOriginalImageDisplay_yORb->setObjectName(QString::fromUtf8("lbOriginalImageDisplay_yORb"));
        lbOriginalImageDisplay_yORb->setGeometry(QRect(445, 318, 138, 138));
        lbOriginalImageDisplay_yORb->setStyleSheet(QString::fromUtf8("background-color:rgb(200, 200, 200)"));
        lbOriginalImageDisplay_k = new QLabel(centralWidget);
        lbOriginalImageDisplay_k->setObjectName(QString::fromUtf8("lbOriginalImageDisplay_k"));
        lbOriginalImageDisplay_k->setGeometry(QRect(700, 318, 138, 138));
        lbOriginalImageDisplay_k->setStyleSheet(QString::fromUtf8("background-color:rgb(200, 200, 200)"));
        lbColor1 = new QLabel(centralWidget);
        lbColor1->setObjectName(QString::fromUtf8("lbColor1"));
        lbColor1->setGeometry(QRect(440, 280, 81, 16));
        lbColor2 = new QLabel(centralWidget);
        lbColor2->setObjectName(QString::fromUtf8("lbColor2"));
        lbColor2->setGeometry(QRect(700, 280, 81, 16));
        lbColor3 = new QLabel(centralWidget);
        lbColor3->setObjectName(QString::fromUtf8("lbColor3"));
        lbColor3->setGeometry(QRect(440, 470, 81, 16));
        lbColor4 = new QLabel(centralWidget);
        lbColor4->setObjectName(QString::fromUtf8("lbColor4"));
        lbColor4->setGeometry(QRect(700, 470, 81, 16));
        pBstartLayering = new QPushButton(centralWidget);
        pBstartLayering->setObjectName(QString::fromUtf8("pBstartLayering"));
        pBstartLayering->setGeometry(QRect(478, 620, 56, 56));
        pBloadImage = new QPushButton(centralWidget);
        pBloadImage->setObjectName(QString::fromUtf8("pBloadImage"));
        pBloadImage->setGeometry(QRect(130, 270, 111, 41));
        pBloadImage->setStyleSheet(QString::fromUtf8("background-color: rgba(250, 250, 250, 0);\n"
"border: 1px solid black;\n"
"border-color: rgba(250, 250, 250, 0);"));
        dSBcAdjustmentCoefficient = new QDoubleSpinBox(centralWidget);
        dSBcAdjustmentCoefficient->setObjectName(QString::fromUtf8("dSBcAdjustmentCoefficient"));
        dSBcAdjustmentCoefficient->setGeometry(QRect(470, 280, 46, 22));
        dSBcAdjustmentCoefficient->setMaximum(3.000000000000000);
        dSBcAdjustmentCoefficient->setSingleStep(0.010000000000000);
        dSBmAdjustmentCoefficient = new QDoubleSpinBox(centralWidget);
        dSBmAdjustmentCoefficient->setObjectName(QString::fromUtf8("dSBmAdjustmentCoefficient"));
        dSBmAdjustmentCoefficient->setGeometry(QRect(730, 280, 46, 22));
        dSBmAdjustmentCoefficient->setMaximum(3.000000000000000);
        dSBmAdjustmentCoefficient->setSingleStep(0.010000000000000);
        dSByAdjustmentCoefficient = new QDoubleSpinBox(centralWidget);
        dSByAdjustmentCoefficient->setObjectName(QString::fromUtf8("dSByAdjustmentCoefficient"));
        dSByAdjustmentCoefficient->setGeometry(QRect(470, 470, 46, 22));
        dSByAdjustmentCoefficient->setMaximum(3.000000000000000);
        dSByAdjustmentCoefficient->setSingleStep(0.010000000000000);
        dSBkAdjustmentCoefficient = new QDoubleSpinBox(centralWidget);
        dSBkAdjustmentCoefficient->setObjectName(QString::fromUtf8("dSBkAdjustmentCoefficient"));
        dSBkAdjustmentCoefficient->setGeometry(QRect(720, 470, 46, 22));
        dSBkAdjustmentCoefficient->setMaximum(3.000000000000000);
        dSBkAdjustmentCoefficient->setSingleStep(0.010000000000000);
        pBsaveScheme = new QPushButton(centralWidget);
        pBsaveScheme->setObjectName(QString::fromUtf8("pBsaveScheme"));
        pBsaveScheme->setGeometry(QRect(460, 18, 75, 24));
        pBsaveScheme->setMinimumSize(QSize(44, 24));
        pBsaveScheme->setStyleSheet(QString::fromUtf8(""));
        label_23 = new QLabel(centralWidget);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(28, 18, 28, 26));
        QFont font;
        font.setPointSize(10);
        font.setBold(true);
        font.setWeight(75);
        label_23->setFont(font);
        pbNewScheme = new QPushButton(centralWidget);
        pbNewScheme->setObjectName(QString::fromUtf8("pbNewScheme"));
        pbNewScheme->setGeometry(QRect(610, 18, 75, 24));
        pbNewScheme->setMinimumSize(QSize(44, 24));
        pbNewScheme->setStyleSheet(QString::fromUtf8(""));
        cbStartInScheme = new QCheckBox(centralWidget);
        cbStartInScheme->setObjectName(QString::fromUtf8("cbStartInScheme"));
        cbStartInScheme->setGeometry(QRect(700, 24, 107, 16));
        pbOpenScheme = new QPushButton(centralWidget);
        pbOpenScheme->setObjectName(QString::fromUtf8("pbOpenScheme"));
        pbOpenScheme->setGeometry(QRect(385, 18, 75, 24));
        pbOpenScheme->setMinimumSize(QSize(44, 24));
        pbOpenScheme->setStyleSheet(QString::fromUtf8(""));
        pBsaveSchemeAs = new QPushButton(centralWidget);
        pBsaveSchemeAs->setObjectName(QString::fromUtf8("pBsaveSchemeAs"));
        pBsaveSchemeAs->setGeometry(QRect(535, 18, 75, 24));
        pBsaveSchemeAs->setMinimumSize(QSize(56, 24));
        pBsaveSchemeAs->setStyleSheet(QString::fromUtf8(""));
        leSchemeDameDisplay = new QLineEdit(centralWidget);
        leSchemeDameDisplay->setObjectName(QString::fromUtf8("leSchemeDameDisplay"));
        leSchemeDameDisplay->setGeometry(QRect(64, 20, 321, 20));
        hSColorSaturation = new QSlider(centralWidget);
        hSColorSaturation->setObjectName(QString::fromUtf8("hSColorSaturation"));
        hSColorSaturation->setGeometry(QRect(70, 464, 191, 21));
        hSColorSaturation->setMaximum(100);
        hSColorSaturation->setSingleStep(0);
        hSColorSaturation->setPageStep(1);
        hSColorSaturation->setValue(0);
        hSColorSaturation->setOrientation(Qt::Horizontal);
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(24, 469, 54, 12));
        lbColorSaturationDisplay = new QLabel(centralWidget);
        lbColorSaturationDisplay->setObjectName(QString::fromUtf8("lbColorSaturationDisplay"));
        lbColorSaturationDisplay->setGeometry(QRect(270, 430, 54, 31));
        label_13 = new QLabel(centralWidget);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(24, 99, 31, 16));
        lbImageName = new QLabel(centralWidget);
        lbImageName->setObjectName(QString::fromUtf8("lbImageName"));
        lbImageName->setGeometry(QRect(56, 100, 551, 16));
        sBccOriginal = new QSpinBox(centralWidget);
        sBccOriginal->setObjectName(QString::fromUtf8("sBccOriginal"));
        sBccOriginal->setGeometry(QRect(621, 160, 50, 22));
        sBccOriginal->setMaximum(100);
        sBccOriginal->setValue(100);
        sBcmOriginal = new QSpinBox(centralWidget);
        sBcmOriginal->setObjectName(QString::fromUtf8("sBcmOriginal"));
        sBcmOriginal->setGeometry(QRect(621, 190, 50, 22));
        sBcmOriginal->setMaximum(100);
        sBcyOriginal = new QSpinBox(centralWidget);
        sBcyOriginal->setObjectName(QString::fromUtf8("sBcyOriginal"));
        sBcyOriginal->setGeometry(QRect(621, 220, 50, 22));
        sBcyOriginal->setMaximum(100);
        sBmmOriginal = new QSpinBox(centralWidget);
        sBmmOriginal->setObjectName(QString::fromUtf8("sBmmOriginal"));
        sBmmOriginal->setGeometry(QRect(881, 190, 50, 22));
        sBmmOriginal->setMaximum(100);
        sBmmOriginal->setValue(100);
        sBmyOriginal = new QSpinBox(centralWidget);
        sBmyOriginal->setObjectName(QString::fromUtf8("sBmyOriginal"));
        sBmyOriginal->setGeometry(QRect(881, 220, 50, 22));
        sBmyOriginal->setMaximum(100);
        sBmcOriginal = new QSpinBox(centralWidget);
        sBmcOriginal->setObjectName(QString::fromUtf8("sBmcOriginal"));
        sBmcOriginal->setGeometry(QRect(881, 160, 50, 22));
        sBmcOriginal->setMaximum(100);
        sBymOriginal = new QSpinBox(centralWidget);
        sBymOriginal->setObjectName(QString::fromUtf8("sBymOriginal"));
        sBymOriginal->setGeometry(QRect(621, 370, 50, 22));
        sBymOriginal->setMaximum(100);
        sByyOriginal = new QSpinBox(centralWidget);
        sByyOriginal->setObjectName(QString::fromUtf8("sByyOriginal"));
        sByyOriginal->setGeometry(QRect(621, 400, 50, 22));
        sByyOriginal->setMaximum(100);
        sByyOriginal->setValue(100);
        sBycOriginal = new QSpinBox(centralWidget);
        sBycOriginal->setObjectName(QString::fromUtf8("sBycOriginal"));
        sBycOriginal->setGeometry(QRect(621, 340, 50, 22));
        sBycOriginal->setMaximum(100);
        dsbLineDistanceC = new QDoubleSpinBox(centralWidget);
        dsbLineDistanceC->setObjectName(QString::fromUtf8("dsbLineDistanceC"));
        dsbLineDistanceC->setGeometry(QRect(620, 250, 50, 22));
        dsbLineDistanceC->setDecimals(3);
        dsbLineDistanceC->setMinimum(0.000000000000000);
        dsbLineDistanceC->setMaximum(1000000000000000019884624838656.000000000000000);
        dsbLineDistanceC->setSingleStep(0.001000000000000);
        dsbLineDistanceC->setValue(0.100000000000000);
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(590, 250, 31, 21));
        dsbLineDistanceM = new QDoubleSpinBox(centralWidget);
        dsbLineDistanceM->setObjectName(QString::fromUtf8("dsbLineDistanceM"));
        dsbLineDistanceM->setGeometry(QRect(880, 250, 50, 22));
        dsbLineDistanceM->setDecimals(3);
        dsbLineDistanceM->setMinimum(0.000000000000000);
        dsbLineDistanceM->setMaximum(1000000000000000019884624838656.000000000000000);
        dsbLineDistanceM->setSingleStep(0.001000000000000);
        dsbLineDistanceM->setValue(0.100000000000000);
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(850, 250, 31, 21));
        label_17 = new QLabel(centralWidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(590, 160, 31, 21));
        label_18 = new QLabel(centralWidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(590, 190, 31, 21));
        label_19 = new QLabel(centralWidget);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(590, 220, 31, 21));
        label_20 = new QLabel(centralWidget);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(850, 190, 31, 21));
        label_21 = new QLabel(centralWidget);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(850, 220, 31, 21));
        label_22 = new QLabel(centralWidget);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(850, 160, 31, 21));
        dsbLineDistanceY = new QDoubleSpinBox(centralWidget);
        dsbLineDistanceY->setObjectName(QString::fromUtf8("dsbLineDistanceY"));
        dsbLineDistanceY->setGeometry(QRect(620, 430, 50, 22));
        dsbLineDistanceY->setDecimals(3);
        dsbLineDistanceY->setMinimum(0.000000000000000);
        dsbLineDistanceY->setMaximum(1000000000000000019884624838656.000000000000000);
        dsbLineDistanceY->setSingleStep(0.001000000000000);
        dsbLineDistanceY->setValue(0.100000000000000);
        label_15 = new QLabel(centralWidget);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(590, 430, 31, 20));
        label_24 = new QLabel(centralWidget);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(590, 370, 31, 21));
        label_25 = new QLabel(centralWidget);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(590, 400, 31, 21));
        label_26 = new QLabel(centralWidget);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(590, 340, 31, 21));
        label_16 = new QLabel(centralWidget);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(850, 430, 31, 16));
        dsbLineDistanceK = new QDoubleSpinBox(centralWidget);
        dsbLineDistanceK->setObjectName(QString::fromUtf8("dsbLineDistanceK"));
        dsbLineDistanceK->setGeometry(QRect(880, 430, 50, 22));
        dsbLineDistanceK->setDecimals(3);
        dsbLineDistanceK->setMinimum(0.000000000000000);
        dsbLineDistanceK->setMaximum(1000000000000000019884624838656.000000000000000);
        dsbLineDistanceK->setSingleStep(0.001000000000000);
        dsbLineDistanceK->setValue(0.100000000000000);
        cmbDrawLnType = new QComboBox(centralWidget);
        cmbDrawLnType->addItem(QString());
        cmbDrawLnType->addItem(QString());
        cmbDrawLnType->setObjectName(QString::fromUtf8("cmbDrawLnType"));
        cmbDrawLnType->setGeometry(QRect(430, 550, 71, 21));
        label = new QLabel(centralWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(170, 550, 31, 21));
        sbGrayLevel = new QSpinBox(centralWidget);
        sbGrayLevel->setObjectName(QString::fromUtf8("sbGrayLevel"));
        sbGrayLevel->setGeometry(QRect(270, 550, 61, 22));
        sbGrayLevel->setMinimum(0);
        sbGrayLevel->setMaximum(256);
        sbGrayLevel->setValue(3);
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(24, 550, 54, 21));
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(360, 550, 54, 21));
        sBimageHeight = new QSpinBox(centralWidget);
        sBimageHeight->setObjectName(QString::fromUtf8("sBimageHeight"));
        sBimageHeight->setGeometry(QRect(100, 550, 61, 22));
        sBimageHeight->setMaximum(1000000000);
        cBblackLayering = new QCheckBox(centralWidget);
        cBblackLayering->setObjectName(QString::fromUtf8("cBblackLayering"));
        cBblackLayering->setGeometry(QRect(530, 550, 81, 21));
        label_14 = new QLabel(centralWidget);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(210, 550, 54, 21));
        line = new QFrame(centralWidget);
        line->setObjectName(QString::fromUtf8("line"));
        line->setGeometry(QRect(24, 500, 941, 16));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(centralWidget);
        line_2->setObjectName(QString::fromUtf8("line_2"));
        line_2->setGeometry(QRect(24, 600, 941, 20));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(centralWidget);
        line_3->setObjectName(QString::fromUtf8("line_3"));
        line_3->setGeometry(QRect(385, 130, 20, 341));
        line_3->setFrameShape(QFrame::VLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(centralWidget);
        line_4->setObjectName(QString::fromUtf8("line_4"));
        line_4->setGeometry(QRect(24, 79, 951, 16));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(590, 540, 80, 40));
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(700, 540, 80, 40));
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setEnabled(true);
        groupBox->setGeometry(QRect(420, 120, 541, 391));
        groupBox->setStyleSheet(QString::fromUtf8("background-color:transparent;\n"
"border:none;"));
        cmBpenNumC = new QComboBox(groupBox);
        cmBpenNumC->addItem(QString());
        cmBpenNumC->addItem(QString());
        cmBpenNumC->addItem(QString());
        cmBpenNumC->addItem(QString());
        cmBpenNumC->addItem(QString());
        cmBpenNumC->addItem(QString());
        cmBpenNumC->addItem(QString());
        cmBpenNumC->addItem(QString());
        cmBpenNumC->addItem(QString());
        cmBpenNumC->setObjectName(QString::fromUtf8("cmBpenNumC"));
        cmBpenNumC->setGeometry(QRect(100, 160, 61, 22));
        cmBpenNumM = new QComboBox(groupBox);
        cmBpenNumM->addItem(QString());
        cmBpenNumM->addItem(QString());
        cmBpenNumM->addItem(QString());
        cmBpenNumM->addItem(QString());
        cmBpenNumM->addItem(QString());
        cmBpenNumM->addItem(QString());
        cmBpenNumM->addItem(QString());
        cmBpenNumM->addItem(QString());
        cmBpenNumM->addItem(QString());
        cmBpenNumM->setObjectName(QString::fromUtf8("cmBpenNumM"));
        cmBpenNumM->setGeometry(QRect(360, 160, 61, 22));
        cmBpenNumY = new QComboBox(groupBox);
        cmBpenNumY->addItem(QString());
        cmBpenNumY->addItem(QString());
        cmBpenNumY->addItem(QString());
        cmBpenNumY->addItem(QString());
        cmBpenNumY->addItem(QString());
        cmBpenNumY->addItem(QString());
        cmBpenNumY->addItem(QString());
        cmBpenNumY->addItem(QString());
        cmBpenNumY->addItem(QString());
        cmBpenNumY->setObjectName(QString::fromUtf8("cmBpenNumY"));
        cmBpenNumY->setGeometry(QRect(100, 350, 61, 22));
        cmBpenNumK = new QComboBox(groupBox);
        cmBpenNumK->addItem(QString());
        cmBpenNumK->addItem(QString());
        cmBpenNumK->addItem(QString());
        cmBpenNumK->addItem(QString());
        cmBpenNumK->addItem(QString());
        cmBpenNumK->addItem(QString());
        cmBpenNumK->addItem(QString());
        cmBpenNumK->addItem(QString());
        cmBpenNumK->addItem(QString());
        cmBpenNumK->setObjectName(QString::fromUtf8("cmBpenNumK"));
        cmBpenNumK->setGeometry(QRect(360, 350, 61, 22));
        cBSelectMorG = new QCheckBox(centralWidget);
        cBSelectMorG->setObjectName(QString::fromUtf8("cBSelectMorG"));
        cBSelectMorG->setGeometry(QRect(820, 140, 71, 16));
        cBSelectMorG->setAutoExclusive(true);
        cBSelectCorR = new QCheckBox(centralWidget);
        cBSelectCorR->setObjectName(QString::fromUtf8("cBSelectCorR"));
        cBSelectCorR->setGeometry(QRect(560, 140, 71, 16));
        cBSelectCorR->setAutoExclusive(true);
        cBSelectYorB = new QCheckBox(centralWidget);
        cBSelectYorB->setObjectName(QString::fromUtf8("cBSelectYorB"));
        cBSelectYorB->setGeometry(QRect(560, 330, 71, 16));
        cBSelectYorB->setAutoExclusive(true);
        cBSelectK = new QCheckBox(centralWidget);
        cBSelectK->setObjectName(QString::fromUtf8("cBSelectK"));
        cBSelectK->setGeometry(QRect(820, 330, 71, 16));
        cBSelectK->setAutoExclusive(true);
        MainWindow->setCentralWidget(centralWidget);
        groupBox->raise();
        lbOriginalImageDisplay->raise();
        lbOriginalImageDisplay_cORr->raise();
        lbOriginalImageDisplay_mORg->raise();
        lbOriginalImageDisplay_yORb->raise();
        lbOriginalImageDisplay_k->raise();
        lbColor1->raise();
        lbColor2->raise();
        lbColor3->raise();
        lbColor4->raise();
        pBstartLayering->raise();
        pBloadImage->raise();
        dSBcAdjustmentCoefficient->raise();
        dSBmAdjustmentCoefficient->raise();
        dSByAdjustmentCoefficient->raise();
        dSBkAdjustmentCoefficient->raise();
        pBsaveScheme->raise();
        label_23->raise();
        pbNewScheme->raise();
        cbStartInScheme->raise();
        pbOpenScheme->raise();
        pBsaveSchemeAs->raise();
        leSchemeDameDisplay->raise();
        hSColorSaturation->raise();
        label_5->raise();
        lbColorSaturationDisplay->raise();
        label_13->raise();
        lbImageName->raise();
        sBccOriginal->raise();
        sBcmOriginal->raise();
        sBcyOriginal->raise();
        sBmmOriginal->raise();
        sBmyOriginal->raise();
        sBmcOriginal->raise();
        sBymOriginal->raise();
        sByyOriginal->raise();
        sBycOriginal->raise();
        dsbLineDistanceC->raise();
        label_7->raise();
        dsbLineDistanceM->raise();
        label_12->raise();
        label_17->raise();
        label_18->raise();
        label_19->raise();
        label_20->raise();
        label_21->raise();
        label_22->raise();
        dsbLineDistanceY->raise();
        label_15->raise();
        label_24->raise();
        label_25->raise();
        label_26->raise();
        label_16->raise();
        dsbLineDistanceK->raise();
        cmbDrawLnType->raise();
        label->raise();
        sbGrayLevel->raise();
        label_8->raise();
        label_11->raise();
        sBimageHeight->raise();
        cBblackLayering->raise();
        label_14->raise();
        line->raise();
        line_2->raise();
        line_3->raise();
        line_4->raise();
        pushButton->raise();
        pushButton_2->raise();
        cBSelectMorG->raise();
        cBSelectCorR->raise();
        cBSelectYorB->raise();
        cBSelectK->raise();
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1000, 23));
        menu = new QMenu(menuBar);
        menu->setObjectName(QString::fromUtf8("menu"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menu->menuAction());

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        lbOriginalImageDisplay->setText(QString());
        lbOriginalImageDisplay_cORr->setText(QString());
        lbOriginalImageDisplay_mORg->setText(QString());
        lbOriginalImageDisplay_yORb->setText(QString());
        lbOriginalImageDisplay_k->setText(QString());
        lbColor1->setText(QApplication::translate("MainWindow", "C(R)", nullptr));
        lbColor2->setText(QApplication::translate("MainWindow", "M(G)", nullptr));
        lbColor3->setText(QApplication::translate("MainWindow", "Y(B)", nullptr));
        lbColor4->setText(QApplication::translate("MainWindow", "K", nullptr));
        pBstartLayering->setText(QApplication::translate("MainWindow", "\347\224\237\346\210\220", nullptr));
        pBloadImage->setText(QApplication::translate("MainWindow", "\345\257\274\345\205\245\345\233\276\347\211\207", nullptr));
        pBsaveScheme->setText(QApplication::translate("MainWindow", "\344\277\235\345\255\230", nullptr));
        label_23->setText(QApplication::translate("MainWindow", "\346\226\271\346\241\210", nullptr));
        pbNewScheme->setText(QApplication::translate("MainWindow", "\346\226\260\345\273\272", nullptr));
        cbStartInScheme->setText(QApplication::translate("MainWindow", "\345\220\257\345\212\250\346\227\266\346\211\223\345\274\200\346\226\271\346\241\210", nullptr));
        pbOpenScheme->setText(QApplication::translate("MainWindow", "\346\211\223\345\274\200", nullptr));
        pBsaveSchemeAs->setText(QApplication::translate("MainWindow", "\344\277\235\345\255\230\344\270\272", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "\351\245\261\345\222\214\345\272\246\357\274\232", nullptr));
        lbColorSaturationDisplay->setText(QString());
        label_13->setText(QApplication::translate("MainWindow", "\346\226\207\344\273\266\357\274\232", nullptr));
        lbImageName->setText(QString());
        label_7->setText(QApplication::translate("MainWindow", "\345\205\211\346\226\221", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "\345\205\211\346\226\221", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "c", nullptr));
        label_18->setText(QApplication::translate("MainWindow", "m", nullptr));
        label_19->setText(QApplication::translate("MainWindow", "y", nullptr));
        label_20->setText(QApplication::translate("MainWindow", "m", nullptr));
        label_21->setText(QApplication::translate("MainWindow", "y", nullptr));
        label_22->setText(QApplication::translate("MainWindow", "c", nullptr));
        label_15->setText(QApplication::translate("MainWindow", "\345\205\211\346\226\221", nullptr));
        label_24->setText(QApplication::translate("MainWindow", "m", nullptr));
        label_25->setText(QApplication::translate("MainWindow", "y", nullptr));
        label_26->setText(QApplication::translate("MainWindow", "c", nullptr));
        label_16->setText(QApplication::translate("MainWindow", "\345\205\211\346\226\221", nullptr));
        cmbDrawLnType->setItemText(0, QApplication::translate("MainWindow", "\346\250\252\347\272\277", nullptr));
        cmbDrawLnType->setItemText(1, QApplication::translate("MainWindow", "\347\253\226\347\272\277", nullptr));

        label->setText(QApplication::translate("MainWindow", "mm", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "\345\233\276\347\211\207\351\253\230\345\272\246\357\274\232", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "\347\233\264\347\272\277\347\261\273\345\236\213\357\274\232", nullptr));
        cBblackLayering->setText(QApplication::translate("MainWindow", "\345\217\215\347\233\270", nullptr));
        label_14->setText(QApplication::translate("MainWindow", "\347\201\260\345\272\246\345\261\202\347\272\247\357\274\232", nullptr));
        pushButton->setText(QApplication::translate("MainWindow", "\347\237\251\351\230\265\346\265\213\350\257\225", nullptr));
        pushButton_2->setText(QApplication::translate("MainWindow", "\345\241\253\345\205\205\346\265\213\350\257\225", nullptr));
        groupBox->setTitle(QString());
        cmBpenNumC->setItemText(0, QApplication::translate("MainWindow", "\347\254\224\345\217\2671", nullptr));
        cmBpenNumC->setItemText(1, QApplication::translate("MainWindow", "\347\254\224\345\217\2672", nullptr));
        cmBpenNumC->setItemText(2, QApplication::translate("MainWindow", "\347\254\224\345\217\2673", nullptr));
        cmBpenNumC->setItemText(3, QApplication::translate("MainWindow", "\347\254\224\345\217\2674", nullptr));
        cmBpenNumC->setItemText(4, QApplication::translate("MainWindow", "\347\254\224\345\217\2675", nullptr));
        cmBpenNumC->setItemText(5, QApplication::translate("MainWindow", "\347\254\224\345\217\2676", nullptr));
        cmBpenNumC->setItemText(6, QApplication::translate("MainWindow", "\347\254\224\345\217\2677", nullptr));
        cmBpenNumC->setItemText(7, QApplication::translate("MainWindow", "\347\254\224\345\217\2678", nullptr));
        cmBpenNumC->setItemText(8, QApplication::translate("MainWindow", "\347\254\224\345\217\2679", nullptr));

        cmBpenNumM->setItemText(0, QApplication::translate("MainWindow", "\347\254\224\345\217\2671", nullptr));
        cmBpenNumM->setItemText(1, QApplication::translate("MainWindow", "\347\254\224\345\217\2672", nullptr));
        cmBpenNumM->setItemText(2, QApplication::translate("MainWindow", "\347\254\224\345\217\2673", nullptr));
        cmBpenNumM->setItemText(3, QApplication::translate("MainWindow", "\347\254\224\345\217\2674", nullptr));
        cmBpenNumM->setItemText(4, QApplication::translate("MainWindow", "\347\254\224\345\217\2675", nullptr));
        cmBpenNumM->setItemText(5, QApplication::translate("MainWindow", "\347\254\224\345\217\2676", nullptr));
        cmBpenNumM->setItemText(6, QApplication::translate("MainWindow", "\347\254\224\345\217\2677", nullptr));
        cmBpenNumM->setItemText(7, QApplication::translate("MainWindow", "\347\254\224\345\217\2678", nullptr));
        cmBpenNumM->setItemText(8, QApplication::translate("MainWindow", "\347\254\224\345\217\2679", nullptr));

        cmBpenNumY->setItemText(0, QApplication::translate("MainWindow", "\347\254\224\345\217\2671", nullptr));
        cmBpenNumY->setItemText(1, QApplication::translate("MainWindow", "\347\254\224\345\217\2672", nullptr));
        cmBpenNumY->setItemText(2, QApplication::translate("MainWindow", "\347\254\224\345\217\2673", nullptr));
        cmBpenNumY->setItemText(3, QApplication::translate("MainWindow", "\347\254\224\345\217\2674", nullptr));
        cmBpenNumY->setItemText(4, QApplication::translate("MainWindow", "\347\254\224\345\217\2675", nullptr));
        cmBpenNumY->setItemText(5, QApplication::translate("MainWindow", "\347\254\224\345\217\2676", nullptr));
        cmBpenNumY->setItemText(6, QApplication::translate("MainWindow", "\347\254\224\345\217\2677", nullptr));
        cmBpenNumY->setItemText(7, QApplication::translate("MainWindow", "\347\254\224\345\217\2678", nullptr));
        cmBpenNumY->setItemText(8, QApplication::translate("MainWindow", "\347\254\224\345\217\2679", nullptr));

        cmBpenNumK->setItemText(0, QApplication::translate("MainWindow", "\347\254\224\345\217\2671", nullptr));
        cmBpenNumK->setItemText(1, QApplication::translate("MainWindow", "\347\254\224\345\217\2672", nullptr));
        cmBpenNumK->setItemText(2, QApplication::translate("MainWindow", "\347\254\224\345\217\2673", nullptr));
        cmBpenNumK->setItemText(3, QApplication::translate("MainWindow", "\347\254\224\345\217\2674", nullptr));
        cmBpenNumK->setItemText(4, QApplication::translate("MainWindow", "\347\254\224\345\217\2675", nullptr));
        cmBpenNumK->setItemText(5, QApplication::translate("MainWindow", "\347\254\224\345\217\2676", nullptr));
        cmBpenNumK->setItemText(6, QApplication::translate("MainWindow", "\347\254\224\345\217\2677", nullptr));
        cmBpenNumK->setItemText(7, QApplication::translate("MainWindow", "\347\254\224\345\217\2678", nullptr));
        cmBpenNumK->setItemText(8, QApplication::translate("MainWindow", "\347\254\224\345\217\2679", nullptr));

        cBSelectMorG->setText(QString());
        cBSelectCorR->setText(QString());
        cBSelectYorB->setText(QString());
        cBSelectK->setText(QString());
        menu->setTitle(QApplication::translate("MainWindow", "\345\205\250\345\275\251\346\212\225\345\275\261", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
